#http://painterlin.com
permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 宋鑫
  email: 504252262@qq.com
  link: http://3gods.com
  weibo: 
  github: http://github.com/songxin1990
  music: http://www.xiami.com/space/lib-song?spm=a1z1s.6928797.226669510.3.wQwdsL
  linkedin: 

# 站点信息
title: 宋鑫的博客
description: My personal blog
url: http://3gods.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-49965095-1
  url: 3gods.com

# disqus 设置
disqus:
  shortname: 3gods

# 主题设置，自动激活某个标签
active: trade

# 首页除了最新文章外显示分类
cates: 
  - trade  
  - mood  

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  mood:随思随想
  trade:交易
  stick:置顶