permalink: /:categories/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: 宋鑫
  email: songxin@3gods.com
  github: http://github.com/songxin1990
  linkedin: https://www.linkedin.com/in/song-xin/
  facebook: https://www.facebook.com/profile.php?id=100018273099120
  twitter: https://twitter.com/songxin1990
  googleplus: https://plus.google.com/110973279070546034423
  zhihu: https://www.zhihu.com/people/3gods

# 站点信息
title: 宋鑫的官方网站
description: 编程，写作，思考，实践，得道
url: http://3gods.com
rss_url: /atom.xml
img_url: http://img.3gods.com

# gavatar头像及Favicon
gavatar: /public/img/fav.ico
favicon: /public/img/fav.ico

# google analytics 设置
ga:
  id: UA-49965095-1
  url: 3gods.com

# disqus 设置
disqus:
  shortname: 3gods

# 首页除了最新文章外显示其他分类
cates:
- essence

# 中文本地化
locals:
  #左侧导航栏
  tags: 标签
  newest: 最新文章
  archive: 归档
  zen: 禅
  essence: 精华文章
  photography: 摄影
  trash: 废弃
  #商业
  business: 商业
  #创作
  essay: 散文
  poem: 诗词
  book: 读书
  review: 读后感
  # 交易
  stock: 股票
  future: 期货
  tradesystem: 交易系统
  # 技术
  bigdata: 大数据
  concurrent: 高并发
  javacore: java核心基础
  opensource: 开源项目
  tools: 开发工具
  project: 项目总结
  database: 数据库
  # 德扑
  porker: 德州扑克
  # 工作
  interview: 求职面试
  career: 职场发展
  # 生活
  dream: 人生梦想
  inspiration: 生活感悟
  # 摄影
  photography: 摄影

# gems 设置
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  #- jekyll-gist


