permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: 宋鑫
  email: 504252262@qq.com
  github: http://github.com/songxin1990
  linkedin: https://www.linkedin.com/in/song-xin/
  zhihu: https://www.zhihu.com/people/3gods

# 站点信息
title: 宋鑫的博客
description: songxin blog
url: http://3gods.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://7xnlfe.com1.z0.glb.clouddn.com/20130304_sunflower.jpg
favicon: http://7xnlfe.com1.z0.glb.clouddn.com/20130304_sunflower.jpg

# google analytics 设置
#ga:
  #id: UA-49965095-1
  #url: 3gods.com

# 主题设置，自动激活某个标签
active: 归档

# 首页除了最新文章外显示其他分类
cates: 
- 精华文章
- 宋鑫1989

# 中文本地化
locals:
  tags: 标签
  newest: 最新文章
  archive: 归档
  zen: 禅
  essence: 精华文章
  photography: 摄影
  # 交易
  stock: 股票
  future: 期货
  tradesystem: 交易系统
  # 技术
  bigdata: 大数据
  concurrent: 高并发
  javacore: java核心基础
  opensource: 开源项目
  tools: 开发工具
  porker: 德州扑克
  # 工作
  interview: 求职面试
  career: 职场发展
  effecthabit: 高效习惯
  # 生活
  dream: 人生梦想
  inspiration: 生活感悟
  # 摄影
  travel: 旅行照片
  lifephoto: 生活照片


# gems 设置
#gems:
  #- jekyll-gist

